name: nfc-player

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: setup go
      uses: actions/setup-go@v3
      with:
        go-version: '1.19.4'
    - name: checkout
      uses: actions/checkout@v2
    - name: build
      run: make pi
